### PR TITLE
pics/* translated to ITA

### PR DESCRIPTION
**Pull request by simonefalcini**
Translated all pics to ITA.
The image dp3t.png has been taken from https://github.com/DP-3T/documents/blob/master/public_engagement/cartoon/it/version_a/onepage.png

### CODE REVIEW

**Review by mendaomn — COMMENTED** [review]
Looks good to me!

Just a doubt: in pics/plan.png we are translating from

> "circuit-breaker" lockdown 

to

> "lockdown intermittente"

As I understand it, the circuit-breaker is a single lockdown that could buy us some time, while waiting for a vaccine. I don't have any better idea though

**Review by harisont — COMMENTED** [review]
Amazing jobs, and so fast too! 
I have just a couple perplexities, though:
- `mitigation_vs_suppression.png`:  I very often see "mitigation" and "suppression" translated simply as "mitigazione" e "soppressione". It may be a better translation because it's correct and much closer to English
- `susceptibles.png`: "0%" -> "_lo_ 0%"
- `timeline3.png` (and, as a consequence, `timeline2.png` as well): I would use two nouns "isolamento" and "quarantena" instead of a verb and a noun "isolare" and "quarantena"

**Comment by harisont** [comment]
> Looks good to me!
> 
> Just a doubt: in pics/plan.png we are translating from
> 
> > "circuit-breaker" lockdown
> 
> to
> 
> > "lockdown intermittente"
> 
> As I understand it, the circuit-breaker is a single lockdown that could buy us some time, while waiting for a vaccine. I don't have any better idea though

I agree, maybe we can leave the English there? Not sure that would be clear to everyone, though

**Comment by simonefalcini** [comment]
> > Looks good to me!
> > Just a doubt: in pics/plan.png we are translating from
> > > "circuit-breaker" lockdown
> > 
> > 
> > to
> > > "lockdown intermittente"
> > 
> > 
> > As I understand it, the circuit-breaker is a single lockdown that could buy us some time, while waiting for a vaccine. I don't have any better idea though
> 
> I agree, maybe we can leave the English there? Not sure that would be clear to everyone, though

We could say "Se non è abbastanza per R<1, integriamo con  Mascherine Per Tutti e/o dei lockdown, fino a quando potremo... "

**Pull request merged**
